version: "2"

services:
  web1:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - redis
    ports:
      - "8085:80"
      
  redis:
    image: redis
  redis2:
    image: redis
  web2: 
    build:
      context: .
      dockerfile: Dockerfile_v2
    links:
      - redis2
    ports:
      - "8086:80"
  balancer:
#    build:
#      context: .
#      dockerfile: Dockerfile_lb
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    links:
      - web1
      - web2
    ports:
      - "8082:80"
    
